Epitome-master/Eisegesis/urls.py
from django.conf.urls import url
from Eisegesis import views

urlpatterns = [
	#/eisegesis/
	url(r'^$', views.index, name='index'),
	#/eisegesis/5/
	url(r'^(?P<proposals_id>[0-9]+)/$', views.moreInfo, name='moreInfo'),
	#/eisegesis/5/vote
	url(r'^(?P<proposals_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

Epitome-master/Epitome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Agora import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', views.homePage, name='home'),
    url(r'^user/', include('Propylaea.urls', namespace="Propylaea")),
    url(r'^eisegesis/', include('Eisegesis.urls', namespace="Eisegesis"))
]

urlpatterns += staticfiles_urlpatterns()

Epitome-master/Eisegesis/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group


class ProposalCat(models.Model):
	PCAT_CAT = models.CharField(max_length=100)                            #the category of the proposal
	def __unicode__(self):
		return self.PCAT_CAT


class Proposals(models.Model):
	P_CODE = models.CharField(max_length=200)                              #the code of the proposal
	P_TITLE = models.CharField(max_length=100)                             #the title of the proposal
	P_SHRBODY = models.CharField(max_length=300)                           #the short body of the proposal
	P_BODY = models.CharField(max_length=1000)                             #the body (main text) of the proposal
	P_CREATION = models.DateTimeField(default = timezone.now())            #the creation date and time of the proposal
	P_STARTDT = models.DateTimeField()                                     #the starting date and time of the proposal
	P_ENDDT = models.DateTimeField()                                       #the ending date and time of the proposal
	P_DURATION = models.IntegerField(default=0)                            #the duration of the proposal
	P_CODE2 = models.CharField(max_length=200, blank = True)               #the code2 of the proposal (protocol number, approval number)
	USER_CREATORID = models.ForeignKey(User, on_delete=models.CASCADE)     #the user (admin) who created the proposal
	UGRP_GROUPID = models.ForeignKey(Group, on_delete=models.CASCADE)      #the group of the user that created the proposal
	PCAT_CAT = models.ForeignKey(ProposalCat)                              #the category of the proposal
	#PCHOICE_CHOICE = models.ForeignKey(ProposalChoice)                    #the voting choices of the proposal
	def __unicode__(self): 
		return "%s %s" % (self.P_TITLE, self.P_BODY)


class ProposalChoice(models.Model):
	#PCHOICE_CHOICE = models.IntegerField(default=0)                       #the voting choices of the proposal
	proposals = models.ForeignKey(Proposals, related_name='PChoice')
	PCHOICE_CHOICE = models.CharField(max_length=100)
	PCHOICE_VOTES = models.IntegerField(default=0)
	def __unicode__(self):
		return self.PCHOICE_CHOICE


class Voter(models.Model):
	user = models.ForeignKey(User)
	Proposals = models.ForeignKey(Proposals)

Epitome-master/Eisegesis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages

from .models import Proposals,ProposalChoice,Voter

@login_required
def index(request):
	latest_proposal_list = Proposals.objects.order_by('-P_CREATION')#[:5]
	template = loader.get_template('Eisegesis/index.html')
	context = {
		'latest_proposal_list': latest_proposal_list,
	}
	return HttpResponse(template.render(context, request))


@login_required
def moreInfo(request, proposals_id):
	proposal = get_object_or_404(Proposals, pk=proposals_id)
	#PChoice = get_object_or_404(ProposalChoice)
	template = loader.get_template('Eisegesis/proposal.html')
	nowDt = timezone.localtime(timezone.now())
	context = {
		'proposal': proposal,
		'nowdt': nowDt,
		#'PChoice': PChoice,
	}
	#return render(request, 'polls/detail.html', {'question': question})
	return HttpResponse(template.render(context, request))

@login_required
def vote(request, proposals_id):
	proposal = get_object_or_404(Proposals, pk=proposals_id)
	if Voter.objects.filter(Proposals_id=proposals_id, user_id=request.user.id).exists():
		messages.add_message(request, messages.INFO, 'You have already voted.')
		return HttpResponseRedirect(reverse('Eisegesis:index'))#, args=(proposal.id,)))
	else:
		try:
			selected_choice = proposal.PChoice.get(pk=request.POST['choice'])
		except (KeyError, ProposalChoice.DoesNotExist):						#probably wrong
			# Redisplay the question voting form.
			nowDt = timezone.localtime(timezone.now())
			return render(request, 'Eisegesis/proposal.html', {
				#'question': question,
				'proposal': proposal,
				'nowdt': nowDt,
				'error_message': "You didn't select a choice.",
			})
		else:
			selected_choice.PCHOICE_VOTES += 1
			selected_choice.save()
			v = Voter(user=request.user, Proposals=proposal)
			v.save()
			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a
			# user hits the Back button.
			messages.add_message(request, messages.INFO, 'Vote submited successfully.')
			return HttpResponseRedirect(reverse('Eisegesis:index'))#, args=(proposal.id,)))

#def index(request):
#	return HttpResponse("Hello")

Epitome-master/Eisegesis/templates/Eisegesis/index.html
<!DOCTYPE html> 

{% load staticfiles %}

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <!-- Frameworks -->
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static "vendors/bootstrap/bootstrap.min.css" %}">
    <!-- Bootflat -->
    <link rel="stylesheet" type="text/css" href="{% static "vendors/bootflat/css/bootflat.min.css" %}">
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/f63660f471.js"></script>
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Advent+Pro|Open+Sans+Condensed:300&subset=greek,latin' rel='stylesheet' type='text/css'>
    <!-- Styling -->
    <link rel="stylesheet" type="text/css" href="{% static "resources/css/style.css" %}">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width"> </head>

<body>
    <!-- The page wrapper -->
    <div id="wrapper">
        <!-- Left Sidebar Menu -->
        <div id="sidebar-wrapper">
            <!-- The top part of the Sidebar menu -->
            <div id="sidebar-top">
                <ul id="sidebar-nav-top">
                    <li> <a href="#">Proposals</a> </li>
                    <li> <a href="#">Laws</a> </li>
                    <li> <a href="#">Polls</a> </li>
                    <li> <a href="#">Configuration</a> </li>
                    <li> <a href="#">Constitution</a> </li>
                </ul>
            </div>
            <!-- The bottom part of the sidebar menu -->
            <div id="sidebar-bot">

            </div>
        </div>
        <!-- The NavBar is a basic div. The "nav" style  from bootstrap is not used and may be removed from -->
        <!-- the production release.The navbar contains two divs and they are positioned using bootstraps "pull-left" -->
        <!-- and "pull-right" classes. -->
        <div class="col-md-12 navbar-fixed-top">
            <!-- This is the button that reveals the left sidebar -->
            <ul class="pull-left activate-left-sidebar">
                <li class="top-bar"> <i id="menu-toggle"><a href="#menu-toggle" class="fa fa-bars fa-2x"></a></i> </li>
            </ul>
            <!-- User Buttons -->


            <div class="logout-container pull-right">
                <a href="/user/logout"><img width="30" height="30" src="{% static "resources/img/Reset_button.svg" %}" alt="Image description." /></a>
            </div>


        </div>
        <!-- Cards -->
        <div class="content-wrapper">
            <div class="example">
                <div class="row">
                    <br>
                    <br>
					{% if messages %}
						{% for message in messages %}
							<p>{{ message }}</p>
						{% endfor %}
					{% endif %}
                </div>
                <div class="col-sm-6 col-md-3">
                    {% if latest_proposal_list %} 
					{% for proposal in latest_proposal_list %}
                    <a href="/eisegesis/{{ proposal.id }}/">
                        <div class="thumbnail">
                            <div class="col-xs-12 card-header">
                                <div class="col-xs-4">
                                    <div class="card-icon"> <img src="http://placehold.it/40x40"> </div>
                                </div>
                                <div class="col-xs-8">
                                    <div class="card-info">
                                        <h6>Participation: <span class="info-value red">1300</span></h6>

                                    </div>
                                </div>
                            </div>
                            <div class="caption text-center">
                                <h3>{{ proposal.P_TITLE }}</h3>
                                <h6>By {{ proposal.USER_CREATORID }}</h6>
                                <p>{{ proposal.P_SHRBODY }}</p>
                            </div>
                        </div>
                    </a>
                    {% endfor %} 
                    {% else %}
                    <p>No proposals are available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <!-- JS Files -->
    <!-- Bootstrap -->
    <script src="{% static "vendors/bootstrap/bootstrap.min.css" %}"></script>
    <script src="{% static "vendors/jquery/jquery-2.2.2.min.js" %}"></script>
    <!-- Bootflat -->
    <script src="{% static "vendors/bootflat/js/site.min.js" %}"></script>
    <script src="{% static "vendors/bootflat/js/respond.min.js" %}"></script>
    <script src="{% static "vendors/html5shiv/html5shiv.js" %}"></script>
    <!-- This script reveals and hides the left sidebar (may move it into it's own seperate file) -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            e.stopPropagation();
            $("#wrapper").toggleClass("toggled");
        });
        $("body").click(function () {
            $("#wrapper").removeClass("toggled");
        });
    </script>
</body>

</html>

Epitome-master/Eisegesis/templates/Eisegesis/proposal.html
<!DOCTYPE html>

{% load staticfiles %}

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <!-- Frameworks -->
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static "vendors/bootstrap/bootstrap.min.css" %}">
    <!-- Bootflat -->
    <link rel="stylesheet" type="text/css" href="{% static "vendors/bootflat/css/bootflat.min.css" %}">
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/f63660f471.js"></script>
    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Advent+Pro|Open+Sans+Condensed:300&subset=greek,latin' rel='stylesheet' type='text/css'>
    <!-- Styling -->
    <link rel="stylesheet" type="text/css" href="{% static "resources/css/style.css"" %}">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width"> </head>

<body>
    <!-- The page wrapper -->
    <div id="wrapper">
        <!-- Left Sidebar Menu -->
        <!-- The NavBar is a basic div. The "nav" style  from bootstrap is not used and may be removed from -->
        <!-- the production release.The navbar contains two divs and they are positioned using bootstraps "pull-left" -->
        <!-- and "pull-right" classes. -->
        <div class="col-md-12 navbar-fixed-top">
            <!-- This is the button that reveals the left sidebar -->
            <ul class="pull-left activate-left-sidebar">
                <li> <i><a href="/eisegesis/" class="fa fa-times fa-2x proposal-close"></a></i> </li>
            </ul>
        </div>
        <div class="content-wrapper top60">
            <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
                <div class="thumbnail">
                    <div class="col-xs-12 card-header">
                        <div class="col-xs-4">
                            <div class="card-icon"> <img src="http://placehold.it/70x70"> </div>
                        </div>
                        <div class="col-xs-8">
                            <div class="card-info">
                                <h6>Participation: <span class="info-value red">1300</span></h6>
                            </div>
                        </div>
                    </div>
                    <div class="caption text-center">
                        <h3> {{ proposal.P_TITLE }} </h3>
                        <h6>By {{ proposal.USER_CREATORID }} </h6>
                        <p> {{ proposal.P_BODY }} </p>
                        {% if proposal.P_ENDDT > nowdt %} <!--????-->
							<div class="text-center">
								<form action="{% url 'Eisegesis:vote' proposal.id %}" method="post">
								{% csrf_token %}
								{% for choice in proposal.PChoice.all %}
									<button type="submit" name="choice" class="btn btn-primary" value="{{ choice.id }}">{{ choice.PCHOICE_CHOICE }}</button>
									<!--<input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}" />
									<label for="choice{{ forloop.counter }}">{{ choice.PCHOICE_CHOICE }}</label><br />-->
									<!--<input type="submit" name="Pavlos" value="{{ choice.id }}" />-->
								{% endfor %}
								<!--<input type="submit" value="vote" />-->
								</form>
								<!--<button type="button" class="btn btn-primary">Yes</button>
								<button type="button" class="btn btn-primary">Abstain</button>
								<button type="button" class="btn btn-primary">No</button>-->
							</div>
						{% else %}<!--????-->
							<div class="text-center"><!--????-->
							{% for choice in proposal.PChoice.all %}<!--????-->
									<p> {{ choice.PCHOICE_CHOICE }}  =  {{ choice.PCHOICE_VOTES }} </p><!--????-->
							{% endfor %}<!--????-->
							</div><!--????-->
						{% endif %}<!--????-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- JS Files -->
    <!-- Bootstrap -->
    <script src="{% static "vendors/bootstrap/bootstrap.min.js" %}"></script>
    <script src="{% static "vendors/jquery/jquery-2.2.2.min.js" %}"></script>
    <!-- Bootflat -->
    <script src="{% static "vendors/bootflat/js/site.min.js" %}"></script>
    <script src="{% static "vendors/bootflat/js/respond.min.js" %}"></script>
    <script src="{% static "vendors/html5shiv/html5shiv.js" %}"></script>
    <!-- This script reveals and hides the left sidebar (may move it into it's own seperate file) -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            e.stopPropagation();
            $("#wrapper").toggleClass("toggled");
        });
        $("body").click(function () {
            $("#wrapper").removeClass("toggled");
        });
    </script>
</body>

</html>